services:
  backend:
    container_name: gshare-backend
    command: sh ./entrypoints/backend.sh
    build : .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  worker:
    container_name: gshare-worker
    command: sh ./entrypoints/celery.sh
    build : .
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    container_name: gshare-postgres
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    container_name: gshare-redis
    image: redis:6
    ports:
      - "6379:6379"


volumes:
  db-data:
