# Generated by Django 5.1.1 on 2024-09-08 18:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("file", models.FileField(blank=True, null=True, upload_to="raw")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("COMPLETED", "Completed")],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("log_file", models.FileField(upload_to="")),
                ("srt_file", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.IntegerField()),
                ("language", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("start_time", models.IntegerField(default=0)),
                ("end_time", models.IntegerField(default=0)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_processor.video",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
    ]
