# Generated by Django 5.1.1 on 2024-09-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="log_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="video",
            name="srt_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
