# Generated by Django 5.1.1 on 2024-09-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0002_alter_video_log_file_alter_video_srt_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("COMPLETED", "COMPLETED")],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
