# Generated by Django 5.1.1 on 2024-09-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0003_alter_video_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="srt_file",
        ),
    ]
