# Generated by Django 5.1.1 on 2024-09-07 09:59

from django.contrib.auth.models import User
from django.db import migrations
from django.utils import timezone


def create_superuser(apps, schema_editor):
    User.objects.create_superuser(
        username="admin",
        email="admin@localhost",
        password="admin",
        last_login=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = []

    # create a superuser
    operations = [migrations.RunPython(create_superuser)]
